<#
.SYNOPSIS
    将 src 安装到 $PROFILE 父目录下的 Using_UNIX_commands_in_powershell，并写入 $PROFILE 加载路径。

.DESCRIPTION
    1. 若 $PROFILE 文件不存在则自动创建（终端醒目提示），并确保其父目录存在
    2. 复制仓库 src\ 全部文件到：$(Split-Path $PROFILE -Parent)\Using_UNIX_commands_in_powershell\
    3. 在 $PROFILE 中写入（或更新）受标记保护的加载块，逐文件点源加载各函数。

.EXAMPLE
    .\build.ps1
#>
[CmdletBinding()] #启用高级函数特性,使脚本支持参数和错误处理
param(
    [string]$InstallFolderName = 'Using_UNIX_commands_in_powershell' # 安装目录名称
)

$ErrorActionPreference = 'Stop' # 设置错误处理方式为停止脚本执行

# 使用标记保护加载块，精准替换旧代码
$markerBegin = '# >>> Using_UNIX_commands_in_powershell BEGIN' # 加载块开始标记
$markerEnd   = '# <<< Using_UNIX_commands_in_powershell END' # 加载块结束标记
$legacyMarkerBegin = '# >>> windows_use_linux_order BEGIN'
$legacyMarkerEnd   = '# <<< windows_use_linux_order END'
$legacyFolderName  = 'windows_use_linux_order'

$repoRoot = $PSScriptRoot # 仓库根目录,获得脚本所在目录
$srcRoot  = Join-Path $repoRoot 'src' # 源码目录,获取src目录
$loadScript = Join-Path $srcRoot 'load.ps1' # 加载脚本,获取load.ps1文件

# 检查源码是否存在
if (-not (Test-Path -LiteralPath $loadScript)) {
    throw "source code not found: $loadScript" # 抛出异常,停止脚本执行
}
# 检查$PROFILE是否定义
if (-not $PROFILE) {
    throw '$PROFILE is not defined, cannot install.' # 抛出异常,停止脚本执行
}

$profileDir = Split-Path -Parent $PROFILE
if (-not $profileDir) {
    throw "cannot resolve `$PROFILE parent directory: $PROFILE"
}

# 若 $PROFILE 或其父目录不存在，自动创建（不用抛异常）
$profileCreated = $false
if (-not (Test-Path -LiteralPath $PROFILE)) {
    if (-not (Test-Path -LiteralPath $profileDir)) {
        New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
    }
    New-Item -ItemType File -Path $PROFILE -Force | Out-Null
    $profileCreated = $true
}

$installRoot = Join-Path $profileDir $InstallFolderName

Write-Host "source code:     $srcRoot"
Write-Host "install directory: $installRoot"
Write-Host "profile file: $PROFILE"
if ($profileCreated) {
    Write-Host ''
    Write-Host ('=' * 60) -ForegroundColor Yellow
    Write-Host '  $PROFILE not found, automatically created: ' -ForegroundColor Black -BackgroundColor Yellow
    Write-Host "  $PROFILE" -ForegroundColor Black -BackgroundColor Yellow
    Write-Host ('=' * 60) -ForegroundColor Yellow
} else {
    Write-Host 'profile file status: already exists (not created)' -ForegroundColor DarkGray
}
Write-Host ''

# --- 1. 复制 src 到安装目录 ---
if (Test-Path -LiteralPath $installRoot) { # 检查安装目录是否存在
    Remove-Item -LiteralPath $installRoot -Recurse -Force # 删除安装目录
}
New-Item -ItemType Directory -Path $installRoot -Force | Out-Null # 创建安装目录
Copy-Item -Path (Join-Path $srcRoot '*') -Destination $installRoot -Recurse -Force # 复制源码到安装目录
Write-Host "copied files to: $installRoot"

# 清理旧版安装目录
$legacyInstall = Join-Path $profileDir $legacyFolderName
if ($legacyInstall -ne $installRoot -and (Test-Path -LiteralPath $legacyInstall)) {
    Remove-Item -LiteralPath $legacyInstall -Recurse -Force
    Write-Host "deleted old install directory: $legacyInstall"
}

# --- 2. 从 load.ps1 解析加载顺序 ---
$relPaths = [System.Collections.Generic.List[string]]::new() # 加载顺序列表
$inArray = $false # 是否在数组中
foreach ($line in Get-Content -LiteralPath (Join-Path $installRoot 'load.ps1') -Encoding UTF8) {
    if ($line -match '\$script:UucipLoadOrder\s*=\s*@\(') { # 如果匹配到这个字符串,作为数组开始
        $inArray = $true # 设置为true,表示在数组中
        continue
    }
    if ($inArray) { # 如果inArray为true,表示在数组中
        if ($line -match '^\s*\)\s*$') { break } # 如果匹配到这个字符串,作为数组结束
        if ($line -match "^\s*'([^']+)'\s*$") {
            $relPaths.Add($Matches[1]) # 添加到加载顺序列表
        }
    }
}
if ($relPaths.Count -eq 0) {
    throw 'cannot parse load order from load.ps1.'
}

foreach ($rel in $relPaths) {
    $p = Join-Path $installRoot $rel
    if (-not (Test-Path -LiteralPath $p)) {
        throw "installation incomplete, missing: $p"
    }
}

# --- 3. 生成 $PROFILE 加载块（展开每个函数文件的路径）---
$block = [System.Collections.Generic.List[string]]::new()
$block.Add($markerBegin)
$block.Add('# automatically generated by build.ps1; running build.ps1 again to update this block')
$block.Add("`$__uucipRoot = Join-Path (Split-Path `$PROFILE -Parent) '$InstallFolderName'")
foreach ($rel in $relPaths) {
    $escaped = $rel.Replace("'", "''")
    $block.Add(". (Join-Path `$__uucipRoot '$escaped')")
}
$block.Add('Remove-Variable __uucipRoot -ErrorAction SilentlyContinue')
$block.Add($markerEnd)

# --- 4. 写入 / 更新 $PROFILE ---
$out = [System.Collections.Generic.List[string]]::new()
$skip = $false
$replaced = $false
foreach ($line in @(Get-Content -LiteralPath $PROFILE -ErrorAction SilentlyContinue)) {
    if ($line -eq $markerBegin -or $line -eq $legacyMarkerBegin) {
        $skip = $true
        foreach ($bl in $block) { $out.Add($bl) }
        $replaced = $true
        continue
    }
    if ($skip) {
        if ($line -eq $markerEnd -or $line -eq $legacyMarkerEnd) { $skip = $false }
        continue
    }
    $out.Add($line)
}
if (-not $replaced) {
    if ($out.Count -gt 0 -and $out[$out.Count - 1] -ne '') {
        $out.Add('')
    }
    foreach ($bl in $block) { $out.Add($bl) }
}

Set-Content -LiteralPath $PROFILE -Value ($out -join [Environment]::NewLine) -Encoding UTF8
Write-Host $(if ($replaced) { "updated load block in `$PROFILE" } else { "appended load block to `$PROFILE" })

Write-Host ''
Write-Host 'installation complete. take effect after reopening PowerShell; or run in current session:'
Write-Host "  . `"$(Join-Path $installRoot 'load.ps1')`""
Write-Host ''
Write-Host 'registered function files:'
foreach ($rel in $relPaths) {
    Write-Host "  $(Join-Path $installRoot $rel)"
}
